name: Continuous Integration

on:
  pull_request:
    branches:
      - main

jobs:
  # Job para testar/compilar o projeto Java
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v6

      - name: Build with Maven
        run: mvn clean install -DskipTests

  # Job para configurar o Docker
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Add support for more platforms with QEMU
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3


  testes:
    runs-on: ubuntu-latest

    steps:
        - name: Check out repository code
          uses: actions/checkout@v6

        - name: Set up Java
          uses: actions/setup-java@v4

          with:
            java-version: '21'
            distribution: 'temurin'

        - name: Run tests
          run: mvn clean test
